[package]
name = "audyo-plaier"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = {version="0.29.0"}
glob = "0.3.2"
ratatui = { version="0.29.0" }
rodio = "0.20.1"
tokio = { version = "1.45.1", features = ["full"] }


